function adjust_fig
set(gca, ...
     'Box'         , 'off'     , ...
     'TickDir'     , 'out'     , ...
     'XMinorTick'  , 'off'      , ...
     'YMinorTick'  , 'off'      , ...
      'YGrid'       , 'off',...
      'XGrid'       , 'off');
set(gca,'LineWidth',1,'FontSize',16,'ticklength',[0.02 0.01]);
%set(gca,'Color',[0.95 0.95 0.95],'FontSize',16,'GridAlpha',1,'GridColor',...
%    [1 1 1],'GridLineWidth',1.5,'LineWidth',1,'TickDir','out','XGrid','on',...
%    'YGrid','on');
colordef white
lgd = legend('Location', 'Best','FontSize',12);
legend('boxoff');
set(lgd, 'color', 'none'); % 设置图例背景透明
legend off
set(gcf,'position',[100 100 380 330])
end